# Sets up a local development environment
version: '3'
services:
  web-app:
    build: ./pictochat-fe
    command: sh -c "npm run build && npm run run-dev-docker"
    environment: 
      - NODE_ENV=development
    ports:
      - '3000:3000' # port configured for webpack dev server
    working_dir: /root/web-app
    volumes:
      - ./pictochat-fe:/root/web-app # mounting local dir to support live reloading
      - /root/web-app/node_modules # effectively unmounts node_modules (solves some problems for Windows hosts)
    depends_on:
      - pictochat-db
  pictochat-db:
    image: mongo:4.0.11
    restart: always
    ports:
      - '27017:27017'
