# Sets up a local development environment
version: "3"
services:
  web-app:
    build:
      dockerfile: ./web-app.Dockerfile
      context: .
    command: sh -c "npm run start-dev-remote"
    env_file:
      - ./.env.dev
    ports:
      - "443:443"
    working_dir: /pictochat
    volumes:
      - .:/pictochat # mounting local dir to support live reloading
      - /pictochat/node_modules # effectively unmounts node_modules (solves some problems for Windows hosts)
    depends_on:
      - pictochat-db
  pictochat-db:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_DB=pictochat
    ports:
      - "5432:5432"
