# Sets up a local development environment
version: '3'
services:
  web-app:
    build: 
        dockerfile: ./build-scripts/web-app.Dockerfile
        context: .
    command: sh -c "npm run start --prefix /pictochat-be && npm run run-dev-docker --prefix /pictochat-fe &"
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    working_dir: /pictochat
    volumes:
      - .:/pictochat # mounting local dir to support live reloading
      - /pictochat/node_modules # effectively unmounts node_modules (solves some problems for Windows hosts)
      - /pictochat/pictochat-fe/node_modules
      - /pictochat/pictochat-be/node_modules
    depends_on:
      - pictochat-db
  pictochat-db:
    image: mongo:4.0.11
    restart: always
    ports:
      - '27017:27017'
